/*
 * This source file was generated by the Gradle 'init' task
 */
package org.yourcompany.yourproject;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
